### ISSUE TITLE
Unable to match mock with same url, headers and method with Alamofire

### ISSUE THREAD

**Issue by fporcaro** [WeTransfer/Mocker#10]
I'm having trouble matching a mock I create with the corresponding actual request being generated from an Alamofire requst, where the url, headers and method all match.

Here's my mock setup:
```
public final class MockedSeriesData {
    public static let exampleJSON: URL = Bundle(for: MockedSeriesData.self).url(forResource: "exampleSeriesList", withExtension: "json")!
}

class SeriesSupportTests: XCTestCase {
        let configuration = URLSessionConfiguration.default
        configuration.protocolClasses = [MockingURLProtocol.self]
        let sessionManager = SessionManager(configuration: configuration)
        
        let originalURL = SeriesSupport.getSeriesListURL()
        let expectation = self.expectation(description: "getAllSeries()")
        
        if let url = originalURL {
            print("Mock URL: \(url)")
            print("Mock URL (absolute): \(url.absoluteString)")
            let mock = Mock(url: url, contentType: .json, statusCode: 200, data: [
                .get : MockedSeriesData.exampleJSON.data 
            ])
            Mocker.register(mock)
            SeriesSupport.getAllSeries(sessionManager: sessionManager, oktaHelper: oktaHelper) { seriesOption, errorOption in
                expectation.fulfill()
                // Evaluate result of completionHandler 
        } else {
            XCTFail( "Unable to unwrap Series List URL" )
        }
        
        waitForExpectations(timeout: 10) { error in
            if let error = error {
                print("Error: \(error.localizedDescription)")
            }
        }
    }
}
```

- I thought maybe I was failing because my headers weren’t matching, so I removed the headers and still wasn’t getting a match.
- I replaced our actual endpoint with <host>, but I have validated it is exactly the same in all print statements

Here’s the real actual Alamofire request:
```
static let PODCAST_SERVICE_BASE_URL_PREFIX = "https://<host>/dev/podcast/"
    static let SERIES_SERVICE_ENDPOINT_SUFFIX = "series"

    class func getSeriesListURL() -> URL? {
        return URL(string: SERIES_SERVICE_ENDPOINT_SUFFIX, relativeTo: URL(string: PODCAST_SERVICE_BASE_URL_PREFIX))
    }

    class func getAllSeries( sessionManager: Alamofire.SessionManager=Alamofire.SessionManager.default, oktaHelper: OktaAuthSupport=OktaAuthHelper() ) {
        if let url = getSeriesListURL() {
            print("URL: \(url)")
            print("URL (absolute): \(url.absoluteString)")
            sessionManager.request(url, method: .get, headers: HTTPHeaders()).responseJSON { response in
                switch response.result {
                case .success(let value):
                    let json = JSON(value)
                    print("JSON: \(json)")
                    // Convert JSON to array and call completion handler with array
                case .failure(let error):
                    print(error)
                    // Call completion handler with error
                }
            }
        }
    }
```

What is getting printed:
```
Mock URL: series -- https://<host>/dev/podcast/
Mock URL (absolute): https://<host>/dev/podcast/series

URL: series -- https://<host>/dev/podcast/
URL (absolute): https://<host>/dev/podcast/series
```

And the error I get from Mocker:
```
com.apple.CFNetwork.CustomProtocols (10): Fatal error: No mocked data found for url Optional("https://<host>/dev/podcast/series") method Optional("GET"). Did you forget to use register()?
```

If I step into the Mocker code, I see my mock registered, but I can't step into the == check where it is evaluating a match on the request to see what is actually getting compared.

Any help would be greatly appreciated!

Frank

**Comment by AvdLee** [comment]
Are you sure that the hosts are the same?

And for what reason are you unable to check the == in the debugger? You should be able to do that 🤔

**Comment by fporcaro** [comment]
It steps right past it. I was hoping to step into it to see what fields are
actually being checked in the given concrete class implementation, but it
skips right over it with a false. Are you able to step into that comparison?

**Comment by fporcaro** [comment]
I was able to step into the ==, not sure why it wasn't stepping into it last time I was debugging.  Once I did, I was able to see that the url == check is failing because it was created with the URL(string:, relativeTo:) initializer.  This surprised me as the absolute strings for both urls were the same.  

If I changed the code in Mock.==() to compare the url.absoluteString, the comparison works. Like so:
`return mock.url.absoluteString == (request.url?.absoluteString ?? "") && mock.data.keys.contains(requestHTTPMethod)`

I am far from an expert in Swift URLs, but it seems like the above code shouldn't break things, but also allow for URLs created using string:relativeTo: (In my probably uninformed opinion, the == on URL should match on absoluteString, since ultimately, I think, that's what gets used).  At least every explanation of why the goofy URL that gets generated by URL(string: relativeTo:) tells you that they're the same and if you don't believe that, compare absoluteString() and you'll see).

Let me know if I should submit a pull request with that change.

**Comment by AvdLee** [comment]
Great found! This makes things a lot clearer. Funny thing, this is already been done:

https://github.com/WeTransfer/Mocker/blob/master/Sources/Mock.swift#L164

The only thing to be done is to release a new version of `Mocker`, as I guess you've implemented this framework using CocoaPods for example?

Let me know and I'll look into releasing an update.

**Comment by fporcaro** [comment]
Yes, I'm using CocoaPods - Thanks for taking care of this!

**Comment by AvdLee** [comment]
@fporcaro we just pushed version 1.2.1 which should fix your issue. Closing this issue, but feel free to reopen if the issue still occurs.

**Comment by fporcaro** [comment]
@AvdLee I think we also need to change the == for comparing a mock to the url request
`static func == (mock: Mock, request: URLRequest) -> Bool {
  ...
        return mock.url == request.url && mock.data.keys.contains(requestHTTPMethod)
    }`

should be:
`return mock.url.absoluteString == request.url.absoluteString && mock.data.keys.contains(requestHTTPMethod)`

Which is actually the check that's failing for me (when I try to run the test, where the actual URLRequest is getting passed in from Alamofire.

**Comment by AvdLee** [comment]
ah, alright. Reopening this one. Would you mind creating a PR with a reproducing test for that?

**Comment by fporcaro** [comment]
Missed this, sorry.  I'm doing it now.

**Comment by fporcaro** [comment]
@AvdLee I sent over the pull request and I saw the Travis build failed, but it looked like it was in areas that I didn't touch, so I wasn't sure what was happening there.  Thoughts?

**Comment by AvdLee** [comment]
I missed your PR, sorry for that. I've added my review now, let's continue the discussion there.

**Comment by AvdLee** [comment]
Fixed with https://github.com/WeTransfer/Mocker/pull/12
