### ISSUE TITLE
Pod Install Issue

### ISSUE THREAD

**Issue by sukhaman** [WeTransfer/Mocker#133]
I am trying to install Mocker pod but unable to install it. I have tried Swift Package Manager as well but there is error on both end. Can you please provide update regarding how can I install Mocker pod ?
<img width="856" alt="Screen Shot 2022-10-24 at 9 43 51 AM" src="https://user-images.githubusercontent.com/62219972/197540947-4bf72331-591b-45e7-851a-99ce90ad202d.png">

**Comment by sukhaman** [comment]
<img width="651" alt="Screen Shot 2022-10-24 at 9 44 47 AM" src="https://user-images.githubusercontent.com/62219972/197541106-34ec992c-f80c-4faf-9189-56da875124f9.png">

**Comment by AvdLee** [comment]
@sukhaman we no longer support CocoaPods since SPM is currently mature enough to adopt. We recommend using SPM to install Mocker.

**Comment by antonogarkov** [comment]
Cocoapods are working poorly with SPM and if your project is built around Cocoapods, then you are out of luck here.
