### ISSUE TITLE
XCode 14.3 Archive Issue

### ISSUE THREAD

**Issue by iamitmishra** [WeTransfer/Mocker#146]
We have added Mocker 3.0.1 as package dependency in our project.  When we are running our code with XCode 14.2, its working fine but its **failing with XCode 14.3**

** ARCHIVE FAILED **

```

The following build commands failed:
    SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\.../Release-iphoneos/../Mocker.private.swiftinterface (in target 'Mocker' from project 'Mocker')
    SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\.../Release-iphoneos/.../Mocker.swiftinterface (in target 'Mocker' from project 'Mocker')
(2 failures)
```

**Comment by palowan-ach** [comment]
I've got the similar issue, c.f. the screenshot

<img width="1176" alt="Screenshot 2023-04-16 at 2 51 23 pm" src="https://user-images.githubusercontent.com/83993921/232269138-ea4db22d-7992-44a5-9f00-1c7fda372120.png">
