### ISSUE TITLE
How can I mock a request only when needed?

### ISSUE THREAD

**Issue by gzlboy** [WeTransfer/Mocker#156]
I integrated Mocker according to the documentation and found that all requests without register will also prompt "No mocked data found for url". Can URLs without register be requested directly?

**Comment by brewhitman** [comment]
It sounds like you might be wanting to use the ["opt in" mode](https://github.com/WeTransfer/Mocker/blob/f732d50c87b85927623c858549b3062b5673680f/Sources/Mocker/Mocker.swift#L52), where the Mocker will only handle requests for URL that were registered, and all other requests will be handled normally. For example, you could add this line when setting up the mocker:

```swift
Mocker.mode = .optin
```
