### ISSUE TITLE
'register' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by mouadroaui** [WeTransfer/Mocker#61]
Hello dear team
i don't know why im getting this error 
'register' is inaccessible due to 'internal' protection level

**Comment by thethtun** [comment]
I just imported the source code into unit test module.

**Comment by thethtun** [comment]
Also, please make sure that you are on the latest version (v2.3.0 as of now). If you copied **pod 'Mocker', '~> 1.0.0'** into Podfile, you won't get the latest version.
