### ISSUE TITLE
AppStore binary fails due to Non-public API usage

### ISSUE THREAD

**Issue by LugonjaAleksandar** [WeTransfer/Mocker#97]
I'm trying to upload the app I'm developing including Mocker package for now, to showcase TestFlight build to the team, but the upload fails with a resulting message from Apple: 

TMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Mocker.framework/Mocker: __swift_FORCE_LOAD_$_XCTestSwiftSupport,The app references non-public symbols in ************: __swift_FORCE_LOAD_$_XCTestSwiftSupport. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by LugonjaAleksandar** [comment]
Issue still exists, it's just that maintainers of this repo are not interested in taking a look at this. :(

**Comment by soymonitus** [comment]
Has this been solved?
