### ISSUE TITLE
[Help needed] - Enqueue different responses for same request

### ISSUE THREAD

**Issue by DrAma999** [WeTransfer/Mocker#98]
I'm trying to understand if this is possible, or at least how I can reach something like that.
I have a chain of "promises", let's say that inside this chain I have the same request with the same URL repeated over time.
For instance I have   LoginCheck API that is called three times inside this chain, the first and second time I want it to succeed the third fail. The chain is already packed inside a function.
It seems that mocker creates a dictionary based on URL, since this URL are equal I will get the same mocked responses.
Is there a way to create different mocked responses for the same request in the same test?
Is there something like queueing responses as I've seen in a similar project for Android?
Does someone have any suggestion?
Best,
Andrea

**Comment by Zeno1995** [comment]
I follow it, I also have the same problem!
Enzo
